// Automatically generated by scripts/generate-manifest.ts
// Do not edit this file manually.

// Pre-compiled Regexes for maximum performance on Cloudflare Workers
export const ROUTE_REGEXPS: Array<RegExp> = [
  new RegExp("^/admin/?$"),
  new RegExp("^/robots\\.txt/?$"),
  new RegExp("^/rss\\.xml/?$"),
  new RegExp("^/sitemap\\.xml/?$"),
  new RegExp("^/admin/posts/?$"),
  new RegExp("^/forgot-password/?$"),
  new RegExp("^/login/?$"),
  new RegExp("^/register/?$"),
  new RegExp("^/reset-link/?$"),
  new RegExp("^/verify-email/?$"),
  new RegExp("^/friend-links/?$"),
  new RegExp("^/posts/?$"),
  new RegExp("^/search/?$"),
  new RegExp("^/unsubscribe/?$"),
  new RegExp("^/profile/?$"),
  new RegExp("^/submit-friend-link/?$"),
  new RegExp("^/$"),
  new RegExp("^/post/[^/]+/?$"),
  new RegExp("^/admin/comments/?$"),
  new RegExp("^/admin/friend-links/?$"),
  new RegExp("^/admin/media/?$"),
  new RegExp("^/admin/settings/?$"),
  new RegExp("^/admin/tags/?$"),
  new RegExp("^/admin/posts/edit/[^/]+/?$"),
];

/**
 * Checks if the path matches any valid route.
 * O(n) regex checks, but zero compilation overhead at runtime.
 */
export function isPathValid(path: string): boolean {
  return ROUTE_REGEXPS.some((regex) => regex.test(path));
}
